### ISSUE TITLE
Investigate using bower / yeoman and how that would interact with this folder structure

### ISSUE THREAD

**Issue by pitchandtone** [dnadesign/dna_frontend_boilerplate#14]

**Comment by jedateach** [comment]
I do this in a not-so-automated way.
For a start, I keep the dependencies in a bower.json file.
For less/css I just include things directly from `bower_components/..../.../abc.less` into my site.less file.
For javascript, I add bower_componets paths to the javascript concat.

See my theme here: https://bitbucket.org/burnbright/bootstrap-boilerplate-theme/src

**Comment by wilr** [comment]
Fixed in Helix

> bower install foo

We'd manually update the gruntfile with the files we need
